#!/bin/bash

function send_notification() {
	volume=$(pulsemixer --get-volume | cut -d" " -f1)
	dunstify -a "changevolume" -u low -r "9993" -h int:value:"$volume" "Volume: ${volume}%" -t 2000
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pulsemixer --unmute
	#pamixer -i 5 --allow-boost
	send_notification $1
	;;
down)
	#pamixer -u
	#pamixer -d 5 --allow-boost
	send_notification $1
	;;
mute)
	#pamixer -t
	if [[ $(pulsemixer --get-mute) == 1 ]]; then
		dunstify -i audio-volume-muted-symbolic.symbolic -a "changevolume" -t 2000 -r 9993 -u low "Muted"
	else
		send_notification up
	fi

	;;
esac

